'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("UIElements.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click to display characters.
        '''</summary>
        Friend ReadOnly Property ClickToShowChars() As String
            Get
                Return ResourceManager.GetString("ClickToShowChars", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This is a very large charset (.
        '''</summary>
        Friend ReadOnly Property LargeCharsetPart1() As String
            Get
                Return ResourceManager.GetString("LargeCharsetPart1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Characters), and may take several minutes to display!
        '''Do you wish to display the characters?
        '''You may prefer to make your edits through the &apos;Edit Characters as Text&apos; feature in the Tools menu.
        '''Remember that the smallest change will take a painfully long time..
        '''</summary>
        Friend ReadOnly Property LargeCharsetPart2() As String
            Get
                Return ResourceManager.GetString("LargeCharsetPart2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Large Character Set.
        '''</summary>
        Friend ReadOnly Property LargeCharsetTitle() As String
            Get
                Return ResourceManager.GetString("LargeCharsetTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading characters....
        '''</summary>
        Friend ReadOnly Property LoadingChars() As String
            Get
                Return ResourceManager.GetString("LoadingChars", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No characters!.
        '''</summary>
        Friend ReadOnly Property NoCharacters() As String
            Get
                Return ResourceManager.GetString("NoCharacters", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resizing characters....
        '''</summary>
        Friend ReadOnly Property ResizingChars() As String
            Get
                Return ResourceManager.GetString("ResizingChars", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
